using UnityEngine;

public class PlayerStatic : MonoBehaviour
{
    private float initialDelay = 10f;
    private float maxDelay = 50f;
    private float currentDelay = 0f;
    private bool isStatic = true;

    private void Start()
    {
        currentDelay = Random.Range(initialDelay, maxDelay);
        Invoke("EnableMovement", currentDelay);
    }

    private void Update()
    {
        if (isStatic)
        {
            // Execute qualquer l칩gica adicional enquanto o jogador estiver est치tico, se necess치rio
        }
        else
        {
            // L칩gica de movimento normal do jogador aqui
        }
    }

    private void EnableMovement()
    {
        isStatic = false;
    }
}